export const shopCategories = [
  { value: 'clothing', label: 'Clothing and Apparel' },
  { value: 'footwear', label: 'Footwear' },
  { value: 'beauty', label: 'Beauty and Personal Care' },
  { value: 'electronics', label: 'Electronics and Gadgets' },
  { value: 'home', label: 'Home and Living' },
  { value: 'furniture', label: 'Furniture and Decor' },
  { value: 'groceries', label: 'Groceries and Food Items' },
  { value: 'health', label: 'Health and Wellness' },
  { value: 'sports', label: 'Sports and Fitness' },
  { value: 'kids', label: 'Kids and Baby Products' },
  { value: 'jewelry', label: 'Jewelry and Accessories' },
  { value: 'automotive', label: 'Automotive and Accessories' },
  { value: 'books', label: 'Books and Stationery' },
  { value: 'phones', label: 'Mobile Phones and Accessories' },
  { value: 'computing', label: 'Computers and Office Equipment' },
  { value: 'gaming', label: 'Gaming and Consoles' },
  { value: 'pets', label: 'Pet Supplies' },
  { value: 'tools', label: 'Tools and Hardware' },
  { value: 'arts', label: 'Arts, Crafts and Handmade' },
  { value: 'services', label: 'Digital Products and Services' },
    {value: 'software', label: 'Software & Technology services' },
];
