export type CountryOption = {
  label: string;
  value: string;
  flagClass: string;
};

export const countryOptions: CountryOption[] = [
  { label: 'Afghanistan', value: 'af', flagClass: 'fi fi-af' },
  { label: 'Albania', value: 'al', flagClass: 'fi fi-al fis' },
  { label: 'Algeria', value: 'dz', flagClass: 'fi fi-dz fis' },
  { label: 'Andorra', value: 'ad', flagClass: 'fi fi-ad fis' },
  { label: 'Angola', value: 'ao', flagClass: 'fi fi-ao fis' },
  { label: 'Antigua and Barbuda', value: 'ag', flagClass: 'fi fi-ag fis' },
  { label: 'Argentina', value: 'ar', flagClass: 'fi fi-ar fis' },
  { label: 'Armenia', value: 'am', flagClass: 'fi fi-am fis' },
  { label: 'Aruba', value: 'aw', flagClass: 'fi fi-aw fis' },
  { label: 'Australia', value: 'au', flagClass: 'fi fi-au fis' },
  { label: 'Austria', value: 'at', flagClass: 'fi fi-at fis' },
  { label: 'Azerbaijan', value: 'az', flagClass: 'fi fi-az fis' },
  { label: 'Bahamas', value: 'bs', flagClass: 'fi fi-bs fis' },
  { label: 'Bahrain', value: 'bh', flagClass: 'fi fi-bh fis' },
  { label: 'Bangladesh', value: 'bd', flagClass: 'fi fi-bd fis' },
  { label: 'Barbados', value: 'bb', flagClass: 'fi fi-bb fis' },
  { label: 'Belarus', value: 'by', flagClass: 'fi fi-by fis' },
  { label: 'Belgium', value: 'be', flagClass: 'fi fi-be fis' },
  { label: 'Belize', value: 'bz', flagClass: 'fi fi-bz fis' },
  { label: 'Benin', value: 'bj', flagClass: 'fi fi-bj fis' },
  { label: 'Bermuda', value: 'bm', flagClass: 'fi fi-bm fis' },
  { label: 'Bhutan', value: 'bt', flagClass: 'fi fi-bt fis' },
  { label: 'Bolivia', value: 'bo', flagClass: 'fi fi-bo fis' },
  { label: 'Bosnia and Herzegovina', value: 'ba', flagClass: 'fi fi-ba fis' },
  { label: 'Botswana', value: 'bw', flagClass: 'fi fi-bw fis' },
  { label: 'Brazil', value: 'br', flagClass: 'fi fi-br fis' },
  { label: 'British Virgin Islands', value: 'vg', flagClass: 'fi fi-vg fis' },
  { label: 'Brunei', value: 'bn', flagClass: 'fi fi-bn fis' },
  { label: 'Bulgaria', value: 'bg', flagClass: 'fi fi-bg fis' },
  { label: 'Burkina Faso', value: 'bf', flagClass: 'fi fi-bf fis' },
  { label: 'Burundi', value: 'bi', flagClass: 'fi fi-bi fis' },
  { label: 'Cabo Verde', value: 'cv', flagClass: 'fi fi-cv fis' },
  { label: 'Cambodia', value: 'kh', flagClass: 'fi fi-kh fis' },
  { label: 'Cameroon', value: 'cm', flagClass: 'fi fi-cm fis' },
  { label: 'Canada', value: 'ca', flagClass: 'fi fi-ca fis' },
  { label: 'Cayman Islands', value: 'ky', flagClass: 'fi fi-ky fis' },
  { label: 'Central African Republic', value: 'cf', flagClass: 'fi fi-cf fis' },
  { label: 'Chad', value: 'td', flagClass: 'fi fi-td fis' },
  { label: 'Chile', value: 'cl', flagClass: 'fi fi-cl fis' },
  { label: 'China', value: 'cn', flagClass: 'fi fi-cn fis' },
  { label: 'Colombia', value: 'co', flagClass: 'fi fi-co fis' },
  { label: 'Comoros', value: 'km', flagClass: 'fi fi-km fis' },
  { label: 'Congo – Brazzaville', value: 'cg', flagClass: 'fi fi-cg fis' },
  { label: 'Congo – Kinshasa', value: 'cd', flagClass: 'fi fi-cd fis' },
  { label: 'Costa Rica', value: 'cr', flagClass: 'fi fi-cr fis' },
  { label: 'Côte d’Ivoire', value: 'ci', flagClass: 'fi fi-ci fis' },
  { label: 'Croatia', value: 'hr', flagClass: 'fi fi-hr fis' },
  { label: 'Cuba', value: 'cu', flagClass: 'fi fi-cu fis' },
  { label: 'Curaçao', value: 'cw', flagClass: 'fi fi-cw fis' },
  { label: 'Cyprus', value: 'cy', flagClass: 'fi fi-cy fis' },
  { label: 'Czech Republic', value: 'cz', flagClass: 'fi fi-cz fis' },
  { label: 'Denmark', value: 'dk', flagClass: 'fi fi-dk fis' },
  { label: 'Djibouti', value: 'dj', flagClass: 'fi fi-dj fis' },
  { label: 'Dominica', value: 'dm', flagClass: 'fi fi-dm fis' },
  { label: 'Dominican Republic', value: 'do', flagClass: 'fi fi-do fis' },
  { label: 'Ecuador', value: 'ec', flagClass: 'fi fi-ec fis' },
  { label: 'Egypt', value: 'eg', flagClass: 'fi fi-eg fis' },
  { label: 'El Salvador', value: 'sv', flagClass: 'fi fi-sv fis' },
  { label: 'Equatorial Guinea', value: 'gq', flagClass: 'fi fi-gq fis' },
  { label: 'Eritrea', value: 'er', flagClass: 'fi fi-er fis' },
  { label: 'Estonia', value: 'ee', flagClass: 'fi fi-ee fis' },
  { label: 'Eswatini', value: 'sz', flagClass: 'fi fi-sz fis' },
  { label: 'Ethiopia', value: 'et', flagClass: 'fi fi-et fis' },
  { label: 'Fiji', value: 'fj', flagClass: 'fi fi-fj fis' },
  { label: 'Finland', value: 'fi', flagClass: 'fi fi-fi fis' },
  { label: 'France', value: 'fr', flagClass: 'fi fi-fr fis' },
  { label: 'French Polynesia', value: 'pf', flagClass: 'fi fi-pf fis' },
  { label: 'Gabon', value: 'ga', flagClass: 'fi fi-ga fis' },
  { label: 'Gambia', value: 'gm', flagClass: 'fi fi-gm fis' },
  { label: 'Georgia', value: 'ge', flagClass: 'fi fi-ge fis' },
  { label: 'Germany', value: 'de', flagClass: 'fi fi-de fis' },
  { label: 'Ghana', value: 'gh', flagClass: 'fi fi-gh fis' },
  { label: 'Greece', value: 'gr', flagClass: 'fi fi-gr fis' },
  { label: 'Greenland', value: 'gl', flagClass: 'fi fi-gl fis' },
  { label: 'Grenada', value: 'gd', flagClass: 'fi fi-gd fis' },
  { label: 'Guatemala', value: 'gt', flagClass: 'fi fi-gt fis' },
  { label: 'Guinea', value: 'gn', flagClass: 'fi fi-gn fis' },
  { label: 'Guinea-Bissau', value: 'gw', flagClass: 'fi fi-gw fis' },
  { label: 'Guyana', value: 'gy', flagClass: 'fi fi-gy fis' },
  { label: 'Haiti', value: 'ht', flagClass: 'fi fi-ht fis' },
  { label: 'Honduras', value: 'hn', flagClass: 'fi fi-hn fis' },
  { label: 'Hungary', value: 'hu', flagClass: 'fi fi-hu fis' },
  { label: 'Iceland', value: 'is', flagClass: 'fi fi-is fis' },
  { label: 'India', value: 'in', flagClass: 'fi fi-in fis' },
  { label: 'Indonesia', value: 'id', flagClass: 'fi fi-id fis' },
  { label: 'Iran', value: 'ir', flagClass: 'fi fi-ir fis' },
  { label: 'Iraq', value: 'iq', flagClass: 'fi fi-iq fis' },
  { label: 'Ireland', value: 'ie', flagClass: 'fi fi-ie fis' },
  { label: 'Israel', value: 'il', flagClass: 'fi fi-il fis' },
  { label: 'Italy', value: 'it', flagClass: 'fi fi-it fis' },
  { label: 'Jamaica', value: 'jm', flagClass: 'fi fi-jm fis' },
  { label: 'Japan', value: 'jp', flagClass: 'fi fi-jp fis' },
  { label: 'Jordan', value: 'jo', flagClass: 'fi fi-jo fis' },
  { label: 'Kazakhstan', value: 'kz', flagClass: 'fi fi-kz fis' },
  { label: 'Kenya', value: 'ke', flagClass: 'fi fi-ke fis' },
  { label: 'Kiribati', value: 'ki', flagClass: 'fi fi-ki fis' },
  { label: 'Kuwait', value: 'kw', flagClass: 'fi fi-kw fis' },
  { label: 'Kyrgyzstan', value: 'kg', flagClass: 'fi fi-kg fis' },
  { label: 'Laos', value: 'la', flagClass: 'fi fi-la fis' },
  { label: 'Latvia', value: 'lv', flagClass: 'fi fi-lv fis' },
  { label: 'Lebanon', value: 'lb', flagClass: 'fi fi-lb fis' },
  { label: 'Lesotho', value: 'ls', flagClass: 'fi fi-ls fis' },
  { label: 'Liberia', value: 'lr', flagClass: 'fi fi-lr fis' },
  { label: 'Libya', value: 'ly', flagClass: 'fi fi-ly fis' },
  { label: 'Liechtenstein', value: 'li', flagClass: 'fi fi-li fis' },
  { label: 'Lithuania', value: 'lt', flagClass: 'fi fi-lt fis' },
  { label: 'Luxembourg', value: 'lu', flagClass: 'fi fi-lu fis' },
  { label: 'Madagascar', value: 'mg', flagClass: 'fi fi-mg fis' },
  { label: 'Malawi', value: 'mw', flagClass: 'fi fi-mw fis' },
  { label: 'Malaysia', value: 'my', flagClass: 'fi fi-my fis' },
  { label: 'Maldives', value: 'mv', flagClass: 'fi fi-mv fis' },
  { label: 'Mali', value: 'ml', flagClass: 'fi fi-ml fis' },
  { label: 'Malta', value: 'mt', flagClass: 'fi fi-mt fis' },
  { label: 'Marshall Islands', value: 'mh', flagClass: 'fi fi-mh fis' },
  { label: 'Mauritania', value: 'mr', flagClass: 'fi fi-mr fis' },
  { label: 'Mauritius', value: 'mu', flagClass: 'fi fi-mu fis' },
  { label: 'Mexico', value: 'mx', flagClass: 'fi fi-mx fis' },
    { label: 'Micronesia', value: 'fm', flagClass: 'fi fi-fm fis' },
    { label: 'Moldova', value: 'md', flagClass: 'fi fi-md fis' },
    { label: 'Monaco', value: 'mc', flagClass: 'fi fi-mc fis' },
    { label: 'Mongolia', value: 'mn', flagClass: 'fi fi-mn fis' },
    { label: 'Montenegro', value: 'me', flagClass: 'fi fi-me fis' },
    { label: 'Montserrat', value: 'ms', flagClass: 'fi fi-ms fis' },
    { label: 'Morocco', value: 'ma', flagClass: 'fi fi-ma fis' },
    { label: 'Mozambique', value: 'mz', flagClass: 'fi fi-mz fis' },
    { label: 'Myanmar', value: 'mm', flagClass: 'fi fi-mm fis' },

    { label: 'Namibia', value: 'na', flagClass: 'fi fi-na fis' },
    { label: 'Nauru', value: 'nr', flagClass: 'fi fi-nr fis' },
    { label: 'Nepal', value: 'np', flagClass: 'fi fi-np fis' },
    { label: 'Netherlands', value: 'nl', flagClass: 'fi fi-nl fis' },
    { label: 'New Caledonia', value: 'nc', flagClass: 'fi fi-nc fis' },
    { label: 'New Zealand', value: 'nz', flagClass: 'fi fi-nz fis' },
    { label: 'Nicaragua', value: 'ni', flagClass: 'fi fi-ni fis' },
    { label: 'Niger', value: 'ne', flagClass: 'fi fi-ne fis' },
    { label: 'Nigeria', value: 'ng', flagClass: 'fi fi-ng fis' },
    { label: 'North Korea', value: 'kp', flagClass: 'fi fi-kp fis' },
    { label: 'North Macedonia', value: 'mk', flagClass: 'fi fi-mk fis' },
    { label: 'Northern Mariana Islands', value: 'mp', flagClass: 'fi fi-mp fis' },
    { label: 'Norway', value: 'no', flagClass: 'fi fi-no fis' },

    { label: 'Oman', value: 'om', flagClass: 'fi fi-om fis' },

    { label: 'Pakistan', value: 'pk', flagClass: 'fi fi-pk fis' },
    { label: 'Palau', value: 'pw', flagClass: 'fi fi-pw fis' },
    { label: 'Palestine', value: 'ps', flagClass: 'fi fi-ps fis' },
    { label: 'Panama', value: 'pa', flagClass: 'fi fi-pa fis' },
    { label: 'Papua New Guinea', value: 'pg', flagClass: 'fi fi-pg fis' },
    { label: 'Paraguay', value: 'py', flagClass: 'fi fi-py fis' },
    { label: 'Peru', value: 'pe', flagClass: 'fi fi-pe fis' },
    { label: 'Philippines', value: 'ph', flagClass: 'fi fi-ph fis' },
    { label: 'Poland', value: 'pl', flagClass: 'fi fi-pl fis' },
    { label: 'Portugal', value: 'pt', flagClass: 'fi fi-pt fis' },
    { label: 'Puerto Rico', value: 'pr', flagClass: 'fi fi-pr fis' },

    { label: 'Qatar', value: 'qa', flagClass: 'fi fi-qa fis' },

    { label: 'Romania', value: 'ro', flagClass: 'fi fi-ro fis' },
    { label: 'Russia', value: 'ru', flagClass: 'fi fi-ru fis' },
    { label: 'Rwanda', value: 'rw', flagClass: 'fi fi-rw fis' },

    { label: 'Saint Kitts and Nevis', value: 'kn', flagClass: 'fi fi-kn fis' },
    { label: 'Saint Lucia', value: 'lc', flagClass: 'fi fi-lc fis' },
    { label: 'Saint Vincent and the Grenadines', value: 'vc', flagClass: 'fi fi-vc fis' },
    { label: 'Samoa', value: 'ws', flagClass: 'fi fi-ws fis' },
    { label: 'San Marino', value: 'sm', flagClass: 'fi fi-sm fis' },
    { label: 'São Tomé and Príncipe', value: 'st', flagClass: 'fi fi-st fis' },
    { label: 'Saudi Arabia', value: 'sa', flagClass: 'fi fi-sa fis' },
    { label: 'Senegal', value: 'sn', flagClass: 'fi fi-sn fis' },
    { label: 'Serbia', value: 'rs', flagClass: 'fi fi-rs fis' },
    { label: 'Seychelles', value: 'sc', flagClass: 'fi fi-sc fis' },
    { label: 'Sierra Leone', value: 'sl', flagClass: 'fi fi-sl fis' },
    { label: 'Singapore', value: 'sg', flagClass: 'fi fi-sg fis' },
    { label: 'Slovakia', value: 'sk', flagClass: 'fi fi-sk fis' },
    { label: 'Slovenia', value: 'si', flagClass: 'fi fi-si fis' },
    { label: 'Solomon Islands', value: 'sb', flagClass: 'fi fi-sb fis' },
    { label: 'Somalia', value: 'so', flagClass: 'fi fi-so fis' },
    { label: 'South Africa', value: 'za', flagClass: 'fi fi-za fis' },
    { label: 'South Korea', value: 'kr', flagClass: 'fi fi-kr fis' },
    { label: 'South Sudan', value: 'ss', flagClass: 'fi fi-ss fis' },
    { label: 'Spain', value: 'es', flagClass: 'fi fi-es fis' },
    { label: 'Sri Lanka', value: 'lk', flagClass: 'fi fi-lk fis' },
    { label: 'Sudan', value: 'sd', flagClass: 'fi fi-sd fis' },
    { label: 'Suriname', value: 'sr', flagClass: 'fi fi-sr fis' },
    { label: 'Sweden', value: 'se', flagClass: 'fi fi-se fis' },
    { label: 'Switzerland', value: 'ch', flagClass: 'fi fi-ch fis' },
    { label: 'Syria', value: 'sy', flagClass: 'fi fi-sy fis' },

    { label: 'Taiwan', value: 'tw', flagClass: 'fi fi-tw fis' },
    { label: 'Tajikistan', value: 'tj', flagClass: 'fi fi-tj fis' },
    { label: 'Tanzania', value: 'tz', flagClass: 'fi fi-tz fis' },
    { label: 'Thailand', value: 'th', flagClass: 'fi fi-th fis' },
    { label: 'Togo', value: 'tg', flagClass: 'fi fi-tg fis' },
    { label: 'Tonga', value: 'to', flagClass: 'fi fi-to fis' },
    { label: 'Trinidad and Tobago', value: 'tt', flagClass: 'fi fi-tt fis' },
    { label: 'Tunisia', value: 'tn', flagClass: 'fi fi-tn fis' },
    { label: 'Turkey', value: 'tr', flagClass: 'fi fi-tr fis' },
    { label: 'Turkmenistan', value: 'tm', flagClass: 'fi fi-tm fis' },

    { label: 'Uganda', value: 'ug', flagClass: 'fi fi-ug fis' },
    { label: 'Ukraine', value: 'ua', flagClass: 'fi fi-ua fis' },
    { label: 'United Arab Emirates', value: 'ae', flagClass: 'fi fi-ae fis' },
    { label: 'United Kingdom', value: 'gb', flagClass: 'fi fi-gb fis' },
    { label: 'United States', value: 'us', flagClass: 'fi fi-us fis' },
    { label: 'Uruguay', value: 'uy', flagClass: 'fi fi-uy fis' },
    { label: 'Uzbekistan', value: 'uz', flagClass: 'fi fi-uz fis' },

    { label: 'Vanuatu', value: 'vu', flagClass: 'fi fi-vu fis' },
    { label: 'Vatican City', value: 'va', flagClass: 'fi fi-va fis' },
    { label: 'Venezuela', value: 've', flagClass: 'fi fi-ve fis' },
    { label: 'Vietnam', value: 'vn', flagClass: 'fi fi-vn fis' },

    { label: 'Yemen', value: 'ye', flagClass: 'fi fi-ye fis' },

    { label: 'Zambia', value: 'zm', flagClass: 'fi fi-zm fis' },
    { label: 'Zimbabwe', value: 'zw', flagClass: 'fi fi-zw fis' }

];
