import './global.css';
import Header from './shared/widgets/header/header';
import QueryProvider from './providers/tanstackWrapper';
import { Roboto, Poppins, Jost, Oregano } from 'next/font/google';
import { Toaster } from "react-hot-toast";
export const metadata = {
  title: 'Welcome to user-ui',
  description: 'Generated by create-nx-workspace',
};

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-roboto',
  display: 'swap',
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
  display: 'swap',
});

const jost = Jost({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-jost',
  display: 'swap',
});

const oregano = Oregano({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-oregano',
  display: 'swap',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${roboto.variable}
          ${poppins.variable}
          ${jost.variable}  
          ${oregano.variable}
        `}
      >
        <QueryProvider>
          <Header />
          {children}
          <Toaster position="top-right" reverseOrder={false} />
        </QueryProvider>
      </body>
    </html>
  );
}
