import './global.css';
import { Metadata } from 'next';
import QueryProvider from '@/app/providers/tanstackWrapper';
import React from  'react';
import { Jost, Oregano, Poppins, Roboto } from 'next/font/google';
// import Sidebar from '@/shared/components/sidebar';

export const metadata:Metadata = {
  title: 'Welcome to seller-ui',
  description: 'Generated by create-nx-workspace',
};

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-roboto',
  display: 'swap',
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
  display: 'swap',
});

const jost = Jost({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-jost',
  display: 'swap',
});

const oregano = Oregano({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-oregano',
  display: 'swap',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${roboto.variable}
          ${poppins.variable}
          ${jost.variable}
          ${oregano.variable}
        `}
      >
        <QueryProvider>
          {/*<div className="flex w-full h-full bg-black">*/}
          {/*  <aside className="w-[250px] min-w-[200px] max-w-[300px] border-r border-slate-600 p-4">*/}
          {/*    <Sidebar />*/}
          {/*  </aside>*/}
          {/*  <div className="flex-1 pl-6 h-full">{children}</div>*/}
          {/*</div>*/}
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
