import './global.css';
import { Metadata } from 'next';
import React from 'react';
import { Jost, Oregano, Poppins, Roboto } from 'next/font/google';
import QueryProvider from './providers/tanstackWrapper';
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: 'Welcome to admin-ui',
  description: 'Generated by create-nx-workspace',
};

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-roboto',
  display: 'swap',
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
  display: 'swap',
});

const jost = Jost({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-jost',
  display: 'swap',
});

const oregano = Oregano({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-oregano',
  display: 'swap',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${roboto.variable}
          ${poppins.variable}
          ${jost.variable}
          ${oregano.variable}
        `}
      >
        <QueryProvider>
          {children}
          <Toaster
            position="top-right"
            toastOptions={{
              style: {
                background: "#1e293b", // slate-800
                color: "#fff",
                border: "1px solid #334155",
              },
            }}
          />
        </QueryProvider>
      </body>
    </html>
  );
}
